
# 3. Grad Rates
```{r}
library(tidyverse)
data1 <- df%>%
  mutate(county_name = case_when( 
                                county_code == "36047" ~ "Brooklyn", 
                                county_code == "36081" ~ "Queens", 
                                county_code == "36005" ~ "Bronx",
                                county_code == "36085" ~ "Staten Island"))%>%
  drop_na(county_name)
data1
```

```{r}
data <-Cities %>% 
  drop_na(hs_grads)
#average grad rates in 2015
grad_rates_nyc<- data %>%
  filter(county_code %in% c("Manhattan", "Brooklyn",  "Queens", "Bronx", "Staten Island"))%>%
  group_by(county_code,year)%>%
  summarise(mean_grad = mean(hs_grads))

grad_rates_good <- grad_rates_nyc %>% filter(county_code %in% c("Manhattan", "Brooklyn",  "Queens", "Bronx"))
grad_rates_bad <-  grad_rates_nyc %>% filter(county_code %in% c("Staten Island"))
```


```{r}

ggplot() + 
  geom_point(data = grad_rates_nyc,aes(x = mean_grad, y = county_code, color = factor(year)), size = 4, alpha = .8)+
  geom_line(data = grad_rates_good, aes(x = mean_grad, y = county_code), arrow = arrow(length=unit(0.20,"cm"), ends="last", type = "closed"))+
  geom_line(data = grad_rates_bad, aes(x = mean_grad, y = county_code), arrow = arrow(length=unit(0.30,"cm"), ends="first", type = "closed"))+
  labs(title = "Change in high school graduation rate", 
       x = "Percent Graduated",
       y = "Region")+
  theme_classic()+
  theme(panel.grid.major.x=element_line())+
   scale_x_continuous(
            breaks=seq(50, 100, 2),
            labels = function(x){paste0(x*1, '%')}
            )

```




