---
title: "For meeting Nov 29"
author: Jay Kim
output: github_document
pdf_document: default
editor_options:
  chunk_output_type: inline
---
```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(ggalt)

```


1. Median Income bar
2. AP course - family income
3. Grad Rates

County Fips Codes:
```{r}
la <- df%>%
  mutate(county_name = case_when(county_code == "06111" ~ "Ventura",
                                county_code == "06059" ~ "Orange",
                                county_code == "06071" ~ "San Bernardino",
                                county_code == "06037" ~ "Los Angeles"))%>%
  drop_na(county_name )


tx <- df%>%
  mutate(county_name = case_when(county_code == "48201" ~ "Harris (Houston)", 
                                 county_code == "48157" ~ "Fort Bend", 
                                 county_code == "48339" ~ "Montgomery", 
                                 county_code == "48167" ~ "Galveston"))%>%
  drop_na(county_name)


philly <- df%>%
  mutate(county_name = case_when(county_code == "42101" ~ "Philadelphia", 
                                 county_code == "42045" ~ "Delaware", 
                                 county_code == "42029" ~ "Chester", 
                                 county_code == "42091" ~ "Montomery",
                                 county_code == "42017" ~ "Bucks"))%>%
  drop_na(county_name)

ny <- df%>%
  mutate(county_name = case_when(county_code == "36061" ~ "Manhattan", 
                                 county_code == "36047" ~ "Brooklyn", 
                                 county_code == "36081" ~ "Queens", 
                                 county_code == "36005" ~ "Bronx",
                                 county_code == "36085" ~ "Staten Island"))%>%
  drop_na(county_name)
```

# 1. Median Income bar
Data manip
```{r}
A <- philly %>%
  drop_na(median_income)
income_Philly <- A %>%
  group_by(county_name)%>%
  summarise(mean_inc = mean(median_income))%>%
  mutate(deviation= mean_inc - 78030.84	)%>%
  arrange(desc(mean_inc))

B <- tx %>%
  drop_na(median_income)
income_tx <- B %>%
  group_by(county_name)%>%
  summarise(mean_inc = mean(median_income))%>%
  mutate(deviation= mean_inc - 72739.39)%>%
  arrange(desc(mean_inc))

C <- la %>%
  drop_na(median_income)
income_la <- C %>%
  group_by(county_name)%>%
  summarise(mean_inc = mean(median_income))%>%
  mutate(deviation= mean_inc - 74260.12)%>%
  arrange(desc(mean_inc))

D <- ny %>%
  drop_na(median_income)
income_ny <- D %>%
  group_by(county_name)%>%
  summarise(mean_inc = mean(median_income))%>%
  mutate(deviation= mean_inc - 65819.36)%>%
  arrange(desc(mean_inc))
```

```{r}
ggplot(income_Philly, aes(x = reorder(county_name, deviation), y = deviation,
           fill = deviation >0))+
  geom_bar(stat = "identity")+
  coord_flip()+
  scale_fill_discrete(name = "", labels = c("Below Average", "Above Average"))+
  labs(
    title="Household income",
    subtitle="We can see how each city is above or below the state average, $78,030.84",
    x = "City",
    y = "Amount Difference"
  )+
  theme_bw()

ggplot(income_tx, aes(x = reorder(county_name, deviation), y = deviation,
           fill = deviation >0))+
  geom_bar(stat = "identity")+
  coord_flip()+
  scale_fill_discrete(name = "", labels = c("Below Average", "Above Average"))+
  labs(
    title="Household income",
    subtitle="We can see how each city is above or below the state average, $72,739.39",
    x = "City",
    y = "Amount Difference"
  )+
  theme_bw()

ggplot(income_la, aes(x = reorder(county_name, deviation), y = deviation,
           fill = deviation >0))+
  geom_bar(stat = "identity")+
  coord_flip()+
  scale_fill_discrete(name = "", labels = c("Below Average", "Above Average"))+
  labs(
    title="Household income",
    subtitle="We can see how each city is above or below the state average, $74,260.12",
    x = "City",
    y = "Amount Difference"
  )+
  theme_bw()

ggplot(income_ny, aes(x = reorder(county_name, deviation), y = deviation,
           fill = deviation >0))+
  geom_bar(stat = "identity")+
  coord_flip()+
  scale_fill_discrete(name = "", labels = c("Below Average", "Above Average"))+
  labs(
    title="Household income",
    subtitle="We can see how each city is above or below the state average, $65,819.36",
    x = "City",
    y = "Amount Difference"
  )+
  theme_bw()
```

# 2. AP course - family income
data manip:
phill
```{r}
ap_philly<- philly%>%
  filter(county_name== "Philadelphia")
philly_wealthy <- ap_philly%>%
  filter(median_income>100000)

ap_sub_philly<- philly%>%
  filter(county_name != "Philadelphia")
sub_philly_wealthy <- ap_philly%>%
  filter(median_income>100000)
```
la
```{r}
ap_la<- la%>%
  filter(county_name== "Los Angeles")
la_wealthy <- ap_la%>%
  filter(median_income>100000)

ap_sub_la<- la%>%
  filter(county_name != "Los Angeles")
sub_la_wealthy <- ap_la%>%
  filter(median_income>100000)
```
houston
```{r}
ap_hou<- tx%>%
  filter(county_name== "Harris (Houston)")
hou_wealthy <- ap_hou%>%
  filter(median_income>90000)

ap_sub_hou<- tx%>%
  filter(county_name != "Harris (Houston)")
sub_hou_wealthy <- ap_hou%>%
  filter(median_income>90000)
```
NY
```{r}
ap_ny<- ny%>%
  filter(county_name== "Manhattan")
ny_wealthy <- ap_ny%>%
  filter(median_income>100000)

ap_b_ny<- ny%>%
  filter(county_name == "Bronx")
b_ny_wealthy <- ap_ny%>%
  filter(median_income>100000)

ap_k_ny<- ny%>%
  filter(county_name == "Brooklyn")
k_ny_wealthy <- ap_ny%>%
  filter(median_income>100000)

ap_s_ny<- ny%>%
  filter(county_name == "Staten Island")
s_ny_wealthy <- ap_ny%>%
  filter(median_income>100000)

ap_q_ny<- ny%>%
  filter(county_name == "Queens")
q_ny_wealthy <- ap_ny%>%
  filter(median_income>100000)
```


Graphs:
Houston:
```{r}
ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_hou)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = hou_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Philadelphia",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_sub_hou)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = sub_hou_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Suburbs of Philadelphia",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())
```
Philadelphia : 
```{r}
ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_philly)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = philly_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Philadelphia",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_sub_philly)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = sub_philly_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Suburbs of Philadelphia",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())
```
LA: 
```{r}
ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_la)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = la_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Los Angeles",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_sub_la)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = sub_la_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Suburbs of Los Angeles",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())
```
NYC:
```{r}
ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_q_ny)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = q_ny_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Queens",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_s_ny)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = s_ny_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Staten Island",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_ny)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = ny_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Manhattan",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_b_ny)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = b_ny_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Bronx",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="pink", data = ap_k_ny)+
  geom_density(aes(ratio_students_AP_enrolled), alpha = .2, fill="lightblue",  data = k_ny_wealthy)+
  labs(
    title="Ratio of students enrolled in at least one AP course to the number of 11th and 12th graders.",
    subtitle="Brookyn",
    x="% in AP courses",
    y="Frequency"
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())
```

# 3. Grad Rates
```{r}
data1 <- df%>%
  mutate(county_name = case_when(county_code == "06111" ~ "Ventura",
                                county_code == "06059" ~ "Orange",
                                county_code == "06071" ~ "San Bernardino",
                                county_code == "06037" ~ "Los Angeles",
                                county_code == "48201" ~ "Harris (Houston)", 
                                county_code == "48157" ~ "Fort Bend", 
                                county_code == "48339" ~ "Montgomery", 
                                county_code == "48167" ~ "Galveston",
                                county_code == "42101" ~ "Philadelphia", 
                                county_code == "42045" ~ "Delaware", 
                                county_code == "42029" ~ "Chester", 
                                county_code == "42091" ~ "Montomery",
                                county_code == "42017" ~ "Bucks",
                                county_code == "36061" ~ "Manhattan", 
                                county_code == "36047" ~ "Brooklyn", 
                                county_code == "36081" ~ "Queens", 
                                county_code == "36005" ~ "Bronx",
                                county_code == "36085" ~ "Staten Island"))%>%
  drop_na(county_name)
data1
```

```{r}
data <-data1 %>% 
  drop_na(perc_high_grad)

#average grad rates in 2015
grad_rates_15<- data %>%
  filter(county_name %in% c("Ventura", "Orange", "Los Angeles", "San Bernardino", "Harris", "Fort Bend" , "Montgomery", "Galveston", "Philadelphia", "Delaware", "Chester",  "Montomery", "Bucks" ,"Manhattan", "Brooklyn",  "Queens", "Bronx", "Staten Island"))%>%
  filter(year == '2015')%>%
  group_by(county_name,year)%>%
  summarise(mean_grad_2015 = mean(perc_high_grad))

#average grad rates in 2010
grad_rates_10<- data %>%
  filter(county_name %in% c("Ventura", "Orange", "Los Angeles", "San Bernardino", "Harris", "Fort Bend" , "Montgomery", "Galveston", "Philadelphia", "Delaware", "Chester",  "Montomery", "Bucks" ,"Manhattan", "Brooklyn",  "Queens", "Bronx", "Staten Island"))%>%
  filter(year == '2010')%>%
  group_by(county_name,year)%>%
  summarise(mean_grad_2010 = mean(perc_high_grad))

grad_rate <- inner_join(grad_rates_10, grad_rates_15, by= "county_name")%>%
  select(county_name, year.x, year.y, mean_grad_2010, mean_grad_2015)
```


```{r}
ggplot(grad_rate, aes(y=county_name, x = mean_grad_2015, xend = mean_grad_2010)) + 
        geom_dumbbell(color= "olivedrab", 
                      size=0.75, 
                      point.colour.l="black") +
  labs(title = "Change in high school graduation rate", 
       x = "Percent Graduated",
       y = "Region")+
  theme_classic()+
  theme(panel.grid.major.x=element_line())+
   scale_x_continuous(
            breaks=seq(50, 100, 2),
            labels = function(x){paste0(x*1, '%')}
            )
```




