---
title: "Data Exploration for Pottsville, PA"
output: github_document
---


#Necessary Libraries
```{r}
library(tidyverse)
```

# Import and Clean Data

```{r message=FALSE, warning=FALSE}
pott <- read_csv('/Users/TyPainter1/Desktop/Masters/Fall\ 2020/DS-5610/eda20-team5-project/Data\ Basics/data.csv') %>% filter(msaname15 == 'Pottsville, PA Micro Area') # filter for Pottsville
```

# Adjust Column Names

Most of the columns are hard to understand tried to make it easier
```{r}
pott <- pott %>% 
  mutate(ED_PRXECE_NM = exp(ED_PRXECE)) %>%
  mutate(ED_PRXHQECE_NM = exp(ED_PRXHQECE)) %>%
  mutate(HE_SUPRFND_NM = exp(HE_SUPRFND)) %>%
  mutate(HE_RSEI_NM = exp(HE_RSEI)) %>%
  select(-ED_PRXECE, -ED_PRXHQECE, -HE_SUPRFND, -HE_RSEI)
```

Most of the columns are hard to understand. We tried to make it easier and obvious even without the data dictionary.

```{r}
pott <- pott %>% 
  rename(id = `_id`) %>% 
  rename(geo_id = geoid) %>% 
  rename(metro_areas = in100) %>%
  rename(area_code = msaid15) %>% 
  rename(county_code = countyfips) %>%
  rename(num_under_18 = pop) %>% 
  rename(ratio_students_AP_enrolled = ED_APENR) %>%
  rename(perc_over24_college_degree = ED_ATTAIN) %>%
  rename(perc_18to24_nearby_college_enrolled = ED_COLLEGE) %>%
  rename(perc_3to4_school_enrolled = ED_ECENROL) %>%
  rename(perc_high_grad = ED_HSGRAD) %>%
  rename(score_third_grade_math = ED_MATH) %>%
  rename(score_third_grade_read = ED_READING) %>%
  rename(perc_elementary_school_poverty = ED_SCHPOV) %>% 
  rename(perc_teacher_1and2_years=ED_TEACHXP) %>% 
  rename(num_ECE_nearby = ED_PRXECE_NM) %>% 
  rename(num_high_qual_ECE_nearby = ED_PRXHQECE_NM) %>% 
  rename(perc_supermarket_nearby = HE_FOOD) %>% 
  rename(perc_green_space_access = HE_GREEN) %>%
  rename(days_temp_above90 = HE_HEAT) %>%
  rename(perc_0to64_health_insurance = HE_HLTHINS) %>%
  rename(mean_ozone_amount = HE_OZONE) %>%
  rename(mean_microparticle = HE_PM25) %>%
  rename(perc_housing_vacancy = HE_VACANCY) %>%
  rename(index_walkability = HE_WALK) %>% 
  rename(num_waste_dump_sites = HE_SUPRFND_NM) %>%
  rename(index_air_pollutants = HE_RSEI_NM) %>%
  rename(perc_below100_poverty = SE_POVRATE) %>%
  rename(perc_household_public_assistance = SE_PUBLIC) %>%
  rename(perc_home_ownership = SE_HOME) %>%
  rename(perc_over15_high_skill = SE_OCC) %>%
  rename(median_income=SE_MHE) %>%
  rename(perc_adults_employed = SE_EMPRAT) %>%
  rename(perc_worker_commute_over1hour = SE_JOBPROX) %>%
  rename(perc_single_parent = SE_SINGLE)
```

##Basic Exporlation
```{r}
dim(pott)
head(pott)
summary(pott)
```

```{r message=FALSE, warning=FALSE}
pott %>% # find amount of NAs
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(funs(sum(is.na(.))))
```

```{r}
library(ggplot2)

ggplot(pott, aes(x = num_under_18,)) +
  geom_histogram(aes(y=..density..), binwidth=80) +
  geom_density(col = "red", alpha =.2, fill = "red") +
  facet_wrap(~year)
```

```{r}
pott2 <- pott %>% select(perc_elementary_school_poverty, perc_supermarket_nearby, perc_green_space_access, perc_0to64_health_insurance, perc_below100_poverty, perc_household_public_assistance, perc_home_ownership, perc_adults_employed)

library(ggcorrplot)
ggcorrplot(round(cor(pott2), 2), hc.order = TRUE, # find correlation between poverty variables
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="circle", 
           colors = c("red", "white", "green"), 
           title="Correlogram of Poverty Variables", 
           ggtheme=theme_bw)
```

```{r}
ggplot(pott) +
  geom_point(aes(x = perc_over24_college_degree, y = perc_over15_high_skill, col = median_income)) +
  scale_color_gradient2(low="red1", mid = "yellow1", high="seagreen", midpoint = median(pott$median_income), breaks = c(30000,40000,50000,60000,70000), labels = c("$30K","$40K", "$50K", "$60K", "$70K")) +
  geom_smooth(aes(x = perc_over24_college_degree, y = perc_over15_high_skill), col = "blue", se = FALSE, method = "lm") +
  scale_x_continuous(labels = function(x){paste0(x, "%")}) +
  scale_y_continuous(labels = function(x){paste0(x, "%")}) +
  facet_wrap(~year)
```

```{r}
ggplot(pott) +
  geom_point(aes(y = perc_over24_college_degree, x = perc_over15_high_skill, col = median_income)) +
  scale_color_gradient2(low="red1", mid = "yellow1", high="seagreen", midpoint = median(pott$median_income), breaks = c(30000,40000,50000,60000,70000), labels = c("$30K","$40K", "$50K", "$60K", "$70K")) +
  geom_smooth(aes(y = perc_over24_college_degree, x = perc_over15_high_skill), col = "blue", se = FALSE, method = "lm") +
  scale_x_continuous(labels = function(x){paste0(x, "%")}) +
  scale_y_continuous(labels = function(x){paste0(x, "%")}) +
  facet_wrap(~year)
```


```{r}
pott%>%
  group_by(msaname15)%>%
  filter(year=='2015')%>%
  summarise(city_under_18_pop = sum(num_under_18))%>%
  arrange(desc(city_under_18_pop))%>%
  na.omit(msaname15)
```

