---
title: "Data Exploration for Pottsville, PA"
---


#Necessary Libraries
```{r}
library(tidyverse)
```

# Import and Clean Data

```{r message=FALSE, warning=FALSE}
pott <- read_csv('data.csv') %>% filter(msaname15 == 'Pottsville, PA Micro Area') # filter for Pottsville
```

# Adjust Column Names

Most of the columns are hard to understand tried to make it easier
```{r}
pott <- pott %>% rename(top100 = in100) %>% 
  rename(metro_area = msaid15) %>% 
  rename(ap_placement = ED_APENR) %>% 
  rename(metro_name = msaname15) %>% 
  rename(pop_under_18 = pop)  %>% 
  rename(adult_edu_attainment_perc = ED_ATTAIN) %>% 
  rename(college_per_18_to_24 = ED_COLLEGE) %>% 
  rename(nursey_school_perc = ED_ECENROL) %>% 
  rename(high_grad_rate = ED_HSGRAD) %>% 
  rename(third_grade_math_prof = ED_MATH) %>% 
  rename(third_grade_reading_prof = ED_READING) %>% 
  rename(school_poverty_perc = ED_SCHPOV) %>% 
  rename(perc_teacher_1and2_years = ED_TEACHXP) %>% 
  rename(early_education_centers = ED_PRXECE) %>% 
  rename(egood_early_education_centers = ED_PRXHQECE) %>% 
  rename(access_to_food = HE_FOOD) %>% 
  rename(extreme_heat = HE_HEAT) %>% 
  rename(health_insurance = HE_HLTHINS) %>% 
  rename(ozone_amount = HE_OZONE) %>% 
  rename(access_to_green = HE_GREEN) %>% 
  rename(walkability = HE_WALK) %>% 
  rename(housing_vacancy_rate = HE_VACANCY) %>% 
  rename(waste_dump_sites = HE_SUPRFND) %>% 
  rename(aribone_microparticles = HE_PM25) %>% 
  rename(pollutants = HE_RSEI) %>% 
  rename(home_ownership = SE_HOME) %>% 
  rename(highskill_employee = SE_OCC) %>% 
  rename(median_income = SE_MHE) %>% 
  rename(employment_rate = SE_EMPRAT) %>% 
  rename(commute_duration = SE_JOBPROX) %>% 
  rename(single_head_houses = SE_SINGLE)

pott <- janitor::clean_names(pott)
```

##Basic Exporlation
```{r}
dim(pott)
head(pott)
summary(pott)
```

```{r message=FALSE, warning=FALSE}
pott %>% # find amount of NAs
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(funs(sum(is.na(.))))
```

```{r}
library(ggplot2)

ggplot(pott, aes(x = pop_under_18,)) +
  geom_histogram(aes(y=..density..), binwidth=80) +
  geom_density(col = "red", alpha =.2, fill = "red") +
  facet_wrap(~year)
```

```{r}
pott2 <- pott %>% select(school_poverty_perc, access_to_food, access_to_green, health_insurance,se_povrate, , se_public, home_ownership, employment_rate)

library(ggcorrplot)
ggcorrplot(round(cor(pott2), 2), hc.order = TRUE, # find correlation between poverty variables
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="circle", 
           colors = c("red", "white", "green"), 
           title="Correlogram of Poverty Variables", 
           ggtheme=theme_bw)
```

```{r}
ggplot(pott) +
  geom_point(aes(x = adult_edu_attainment_perc, y = highskill_employee, col = median_income)) +
  scale_color_gradient2(low="red1", mid = "yellow1", high="seagreen", midpoint = median(pott$median_income), breaks = c(30000,40000,50000,60000,70000), labels = c("$30K","$40K", "$50K", "$60K", "$70K")) +
  geom_smooth(aes(x = adult_edu_attainment_perc, y = highskill_employee), col = "blue", se = FALSE, method = "lm") +
  scale_x_continuous(labels = function(x){paste0(x, "%")}) +
  scale_y_continuous(labels = function(x){paste0(x, "%")}) +
  facet_wrap(~year)
```

```{r}
ggplot(pott) +
  geom_point(aes(y = adult_edu_attainment_perc, x = highskill_employee, col = median_income)) +
  scale_color_gradient2(low="red1", mid = "yellow1", high="seagreen", midpoint = median(pott$median_income), breaks = c(30000,40000,50000,60000,70000), labels = c("$30K","$40K", "$50K", "$60K", "$70K")) +
  geom_smooth(aes(y = adult_edu_attainment_perc, x = highskill_employee), col = "blue", se = FALSE, method = "lm") +
  scale_x_continuous(labels = function(x){paste0(x, "%")}) +
  scale_y_continuous(labels = function(x){paste0(x, "%")}) +
  facet_wrap(~year)
```


```{r}
pott%>%
  group_by(metro_name)%>%
  filter(year=='2015')%>%
  summarise(city_under_18_pop = sum(pop_under_18))%>%
  arrange(desc(city_under_18_pop))%>%
  na.omit(metro_name)
```

