---
title: "Data Exploration for PHiladelphia and surrounding Suburbs"
output: github_document
---

# Load Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(readr)
```

# Import Data

```{r message=FALSE, warning=FALSE}
df <- read_csv('/Users/TyPainter1/Desktop/Masters/Fall\ 2020/DS-5610/eda20-team5-project/Data\ Basics/data.csv') 
```

# Clean Data

Most of the columns are hard to understand tried to make it easier
```{r}
df <- df %>% rename(top100 = in100) %>% 
  rename(metro_area = msaid15) %>% 
  rename(ap_placement = ED_APENR) %>% 
  rename(metro_name = msaname15) %>% 
  rename(pop_under_18 = pop)  %>% 
  rename(adult_edu_attainment_perc = ED_ATTAIN) %>% 
  rename(college_per_18_to_24 = ED_COLLEGE) %>% 
  rename(nursey_school_perc = ED_ECENROL) %>% 
  rename(high_grad_rate = ED_HSGRAD) %>% 
  rename(third_grade_math_prof = ED_MATH) %>% 
  rename(third_grade_reading_prof = ED_READING) %>% 
  rename(school_poverty_perc = ED_SCHPOV) %>% 
  rename(perc_teacher_1and2_years = ED_TEACHXP) %>% 
  rename(early_education_centers = ED_PRXECE) %>% 
  rename(egood_early_education_centers = ED_PRXHQECE) %>% 
  rename(access_to_food = HE_FOOD) %>% 
  rename(extreme_heat = HE_HEAT) %>% 
  rename(health_insurance = HE_HLTHINS) %>% 
  rename(ozone_amount = HE_OZONE) %>% 
  rename(access_to_green = HE_GREEN) %>% 
  rename(walkability = HE_WALK) %>% 
  rename(housing_vacancy_rate = HE_VACANCY) %>% 
  rename(waste_dump_sites = HE_SUPRFND) %>% 
  rename(aribone_microparticles = HE_PM25) %>% 
  rename(pollutants = HE_RSEI) %>% 
  rename(home_ownership = SE_HOME) %>% 
  rename(highskill_employee = SE_OCC) %>% 
  rename(median_income = SE_MHE) %>% 
  rename(employment_rate = SE_EMPRAT) %>% 
  rename(commute_duration = SE_JOBPROX) %>% 
  rename(single_head_houses = SE_SINGLE)
df <- janitor::clean_names(df)
```

# Basic Exporlation 

```{r}
# philly <- df %>% filter(metro_name == "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metro Area") %>% # filter Philly area
#   mutate(type = ifelse(countyfips == 42101, "Philadelphia", "Suburb")) # mutate a city, suburb column;City of Phila. is 42101

philly <- df %>% 
  filter(metro_name == "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metro Area") %>% # filter Philly area
  mutate(type = ifelse(countyfips == 42101, "Philadelphia", "Suburb")) %>%  # mutate a city, suburb column;City of Phila. is 42101
  mutate(countyfips = replace(countyfips, countyfips == '10003', 'New Castle (DE)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '24015', 'Cecil (MD)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '34005', 'Burlington (NJ)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '34007', 'Camden (NJ)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '34015', 'Gloucester (NJ)'))%>%
  mutate(countyfips = replace(countyfips, countyfips == '34033', 'Salem (NJ)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '42017', 'Bucks (PA)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '42029', 'Chester (PA)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '42045', 'Delaware (PA)')) %>%
  mutate(countyfips = replace(countyfips, countyfips == '42091', 'Montgomery (PA)'))%>%
  mutate(countyfips = replace(countyfips, countyfips == '42101', 'Philadelphia'))%>%
   mutate_all(~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))

factor(philly$countyfips, levels = c("New Castle (DE)", "Cecil (MD)", "Burlington (NJ)", "Camden (NJ)", "Gloucester (NJ)", "Salem (NJ)", "Bucks (PA)", "Chester (PA)", "Delaware (PA)", "Montgomery (PA)"))

dim(philly)
head(philly)
summary(philly)

philly %>%  group_by(stateusps, type) %>%
  tally(sort = T) %>%
  ungroup() %>%
  arrange(desc(n)) # see the distribution among states                 

philly %>% group_by(countyfips, type, stateusps) %>%
  tally(sort = T) %>%
  ungroup() %>%
  arrange(desc(n)) # see the distribution among counties

philly %>% group_by(type) %>%
  tally(sort = T) %>%
  ungroup() %>%
  arrange(desc(n)) # see the distribution among Philly and suburbs
```

```{r message=FALSE, warning=FALSE}
philly %>% # find amount of NAs
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(funs(sum(is.na(.))))
```

# Exploratory Graphics

```{r}
philly %>% group_by(type, stateusps) %>% 
  summarize(child_population = sum(pop_under_18)) %>% 
  ggplot() +
  geom_col(aes(x = type, y = child_population, fill = reorder(stateusps, child_population)))

philly %>% 
  group_by(stateusps, countyfips) %>% 
  summarize(child_population = sum(pop_under_18)) %>% 
  ggplot(aes(x = reorder(stateusps, child_population), y = child_population, fill = countyfips, label = countyfips)) +
  geom_col() +
  geom_text(size = 3, position = position_stack(vjust = 0.5))

philly %>% group_by(countyfips, stateusps) %>% 
  summarize(child_population = sum(pop_under_18)) %>% 
  ggplot() +
  geom_col(aes(x = reorder(countyfips, child_population), y = child_population, fill = stateusps)) 
```

```{r}
ggplot(philly, aes(x = type, y = home_ownership)) +
  geom_violin() +
  geom_point(position = position_jitter(width = 0.4), alpha = .35, aes(color = stateusps))

ggplot(philly, aes(x = stateusps, y = home_ownership)) +
  geom_violin() +
  geom_point(position = position_jitter(width = 0.4), alpha = .35, aes(color = type)) +
  geom_hline(yintercept = 77.06333, colour = "magenta", linetype = "longdash", size = .4)

a <- philly %>% filter(type == 'Suburb') %>% na.omit()

ggplot(philly, aes(x = countyfips, y = home_ownership)) +
  geom_violin() +
  geom_point(position = position_jitter(width = 0.4), alpha = .35, aes(color = stateusps, shape = type)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

ggplot(philly, aes(x = reorder(countyfips, home_ownership), y = home_ownership)) +
  geom_violin() +
  geom_point(position = position_jitter(width = 0.4), alpha = .35, aes(color = stateusps)) +
  facet_wrap(~year, nrow = 2) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r}
ggplot(philly, aes(x = highskill_employee, y = home_ownership)) +
  geom_point(aes(col = type))

ggplot(philly, aes(x = median_income, y = home_ownership)) +
  geom_point(aes(col = type))
```

```{r}
ggplot(philly, aes(x = type, y = home_ownership)) +
  geom_jitter(alpha=.4)

ggplot(philly, aes(x = type, y = median_income)) +
  geom_jitter(alpha=.4, aes(col = stateusps)) +
  scale_y_continuous(labels = function(x){paste0("$", x/1000, "K")}) 

ggplot(philly, aes(x = type, y =commute_duration)) +
  geom_jitter(alpha=.4, aes(col = stateusps)) +
  labs(y = "Commute > 1 Hour") +
  scale_y_continuous(labels = function(x){paste0(x, "%")}, limits = c(0, 35)) +
  theme_classic() # violin?
```



