---
title: "Texas Economics"
---

# College Degree vs Income

## Graphs
```{r}
library(viridis)
```


```{r}
ggplot(df_tx, aes(x = college_deg, y = median_income))+
  geom_point(aes(color = county_code), alpha = .5)
```

# High Skill vs Income

## Graphs
```{r}
ggplot(df_tx ,aes(x = perc_over15_high_skill, y = median_income))+
geom_point(aes(color = county_code), alpha = .5)
```
# Homeownership

```{r}
ggplot(df_tx, aes(x = reorder(county_code, home_ownership), y = home_ownership)) +
  geom_violin() +
  geom_point(position = position_jitter(width = 0.4), alpha = .35, aes(color = median_income)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  scale_color_viridis(name = "Median Income",
                      labels = function(x){paste0("$", x/1000, "K")}) +
  scale_y_continuous(labels = function(x){paste0(x, "%")}) +
    labs(
    x = "County",
    y = "Home Ownership",
    title = "Home Ownership in Houston and its Suburbs"
  ) +
  geom_hline(yintercept = median(df_tx$home_ownership), color = "red", linetype = "dashed")
```

